CREATE SCHEMA IF NOT EXISTS `sgUsers`;
CREATE SCHEMA IF NOT EXISTS `sgGame`;

USE `sgUsers`;

DROP TABLE IF EXISTS `users`;

CREATE TABLE IF NOT EXISTS `users`(
  `userId` BIGINT(20) UNSIGNED AUTO_INCREMENT,
  `lang` VARCHAR(8) NOT NULL DEFAULT 'en',
  `device` VARCHAR(16) NOT NULL,
  `uuid` VARCHAR(24) NOT NULL UNIQUE,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdAt` DATETIME,
  PRIMARY KEY (`userId`),
  INDEX (`uuid`)
)
ENGINE = InnoDB,
DEFAULT CHARSET=utf8,
COMMENT = 'user information';

USE `sgGame`;

DROP TABLE IF EXISTS `maps`;

CREATE TABLE IF NOT EXISTS `maps`(
  `geohash` VARCHAR(16) NOT NULL UNIQUE,
  `userId` BIGINT(20) UNSIGNED,
  `info` TEXT NOT NULL COMMENT 'compressed map info',
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdAt` DATETIME,
  PRIMARY KEY (`geohash`)
)
ENGINE = InnoDB,
DEFAULT CHARSET=utf8,
COMMENT = 'map database';
