Object.freeze(G_CONST = {
    MAPDATA: 'mapData',
    USERDATA: 'userData',
});

Object.freeze(G_API = {
    MAPDATA_SAVE: G_CONST.MAPDATA + G_CCONST.UPDATE,
    MAPDATA_READ: G_CONST.MAPDATA + G_CCONST.READ,
    USERDATA_READ: G_CONST.USERDATA + G_CCONST.READ,
    USERDATA_CREATE: G_CONST.USERDATA + G_CCONST.CREATE,
});

Object.freeze(G_SESSION = {
    JOBS: G_CONST.JOBS,
    MAPDATA: G_CONST.MAPDATA,
    USERDATA: G_CONST.USERDATA,
});

